# Generated by Django 5.0.6 on 2024-06-06 19:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Articulos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creacion', models.DateField(auto_now_add=True)),
                ('actualizacion', models.DateField(auto_now=True, null=True)),
                ('titulo', models.CharField(max_length=200)),
                ('contenido', models.TextField()),
                ('Encabezado', models.ImageField(blank=True, null=True, upload_to='cross_asistent/static/files/imagenes/')),
                ('autor', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Banners',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=40)),
                ('descripcion', models.CharField(max_length=350)),
                ('articulo', models.CharField(blank=True, max_length=200, null=True)),
                ('imagen', models.ImageField(upload_to='cross_asistent/static/files/banners/')),
                ('expiracion', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Database',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('informacion', models.TextField(blank=True, null=True)),
                ('redirigir', models.URLField(blank=True, null=True)),
                ('documentos', models.FileField(blank=True, null=True, upload_to='cross_asistent/static/files/documentos/')),
                ('imagenes', models.ImageField(blank=True, null=True, upload_to='cross_asistent/static/files/imagenes/')),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Sugerencias_preg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sugerencia', models.TextField()),
                ('sugerente', models.CharField(default='Anonimo', max_length=100)),
                ('pregunta_num', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cross_asistent.database')),
            ],
        ),
        migrations.CreateModel(
            name='Tareas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tarea', models.CharField(max_length=255)),
                ('importante', models.BooleanField(default=False)),
                ('creacion', models.DateTimeField(auto_now_add=True)),
                ('completar', models.BooleanField(default=False)),
                ('completado_fecha', models.DateTimeField(blank=True, null=True)),
                ('propietario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
