# Generated by Django 5.0.6 on 2024-08-01 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cross_asistent', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='banners',
            name='redirigir',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
