# Generated by Django 5.0.6 on 2024-05-16 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cross_asistent', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='preguntas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pregunta', models.CharField(max_length=200)),
                ('respuesta', models.TextField()),
                ('documentos', models.FileField(blank=True, upload_to='referencias_documentos/')),
                ('imagenes', models.ImageField(blank=True, upload_to='referencias_imagenes/')),
            ],
        ),
    ]
