# Generated by Django 5.0.6 on 2024-05-16 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cross_asistent', '0002_preguntas'),
    ]

    operations = [
        migrations.AddField(
            model_name='preguntas',
            name='fecha_modificacion',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='preguntas',
            name='redirigir',
            field=models.URLField(blank=True),
        ),
    ]
