# Generated by Django 5.0.6 on 2024-08-01 17:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cross_asistent', '0002_banners_redirigir'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='banners',
            name='articulo',
        ),
    ]
