# Generated by Django 5.0.6 on 2024-08-25 03:49

import cross_asistent.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cross_asistent', '0002_alter_database_categoria'),
    ]

    operations = [
        migrations.CreateModel(
            name='Configuraciones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qr_image', models.ImageField(blank=True, null=True, upload_to=cross_asistent.models.set_imgProfile_path)),
            ],
        ),
        migrations.AlterField(
            model_name='banners',
            name='redirigir',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='database',
            name='redirigir',
            field=models.TextField(blank=True, null=True),
        ),
    ]
