# Generated by Django 5.0.6 on 2024-06-07 15:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cross_asistent', '0003_keyword_synonym'),
    ]

    operations = [
        migrations.AlterField(
            model_name='synonym',
            name='keyword',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='synonyms', to='cross_asistent.database'),
        ),
        migrations.AddField(
            model_name='database',
            name='frecuencia',
            field=models.IntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='Keyword',
        ),
    ]
