# Generated by Django 5.0.6 on 2024-05-16 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cross_asistent', '0003_preguntas_fecha_modificacion_preguntas_redirigir'),
    ]

    operations = [
        migrations.CreateModel(
            name='banners',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=150)),
                ('descripcion', models.CharField(max_length=200)),
                ('imagen', models.ImageField(upload_to='referencias/banners')),
                ('expiracion', models.DateTimeField(blank=True)),
            ],
        ),
        migrations.AlterField(
            model_name='preguntas',
            name='documentos',
            field=models.FileField(blank=True, upload_to='referencias/documentos/'),
        ),
        migrations.AlterField(
            model_name='preguntas',
            name='imagenes',
            field=models.ImageField(blank=True, upload_to='referencias/imagenes/'),
        ),
    ]
