# Generated by Django 5.0.6 on 2024-08-01 18:16

import cross_asistent.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cross_asistent', '0003_remove_banners_articulo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='database',
            name='documento',
            field=models.FileField(blank=True, null=True, upload_to=cross_asistent.models.set_pdfDB_path),
        ),
    ]
