# Generated by Django 5.0.6 on 2024-08-01 21:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cross_asistent', '0004_alter_database_documento'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='passwoed_update',
            new_name='password_update',
        ),
    ]
