# Generated by Django 5.0.6 on 2024-05-16 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cross_asistent', '0004_banners_alter_preguntas_documentos_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banners',
            name='expiracion',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='preguntas',
            name='documentos',
            field=models.FileField(blank=True, null=True, upload_to='referencias/documentos/'),
        ),
        migrations.AlterField(
            model_name='preguntas',
            name='imagenes',
            field=models.ImageField(blank=True, null=True, upload_to='referencias/imagenes/'),
        ),
        migrations.AlterField(
            model_name='preguntas',
            name='redirigir',
            field=models.URLField(blank=True, null=True),
        ),
    ]
