# Generated by Django 5.0.6 on 2024-08-26 05:32

import cross_asistent.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cross_asistent', '0004_configuraciones_about_img_first_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mapa',
            name='img_marker',
            field=models.ImageField(blank=True, null=True, upload_to=cross_asistent.models.set_imgMarker_path),
        ),
        migrations.AddField(
            model_name='mapa',
            name='is_marker',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='user_token',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='mapa',
            name='door_cords',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='mapa',
            name='p1_polygons',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='mapa',
            name='p2_polygons',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='mapa',
            name='p3_polygons',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='mapa',
            name='p4_polygons',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
