# Generated by Django 5.0.6 on 2024-08-04 06:02

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cross_asistent', '0005_rename_passwoed_update_userprofile_password_update'),
    ]

    operations = [
        migrations.AddField(
            model_name='mapa',
            name='muid',
            field=models.CharField(default=django.utils.timezone.now, max_length=23),
            preserve_default=False,
        ),
    ]
