# Generated by Django 5.0.6 on 2024-08-26 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cross_asistent', '0005_mapa_img_marker_mapa_is_marker_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='database',
            name='uuid',
            field=models.CharField(max_length=25),
        ),
    ]
