# Generated by Django 5.0.6 on 2024-08-04 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cross_asistent', '0006_mapa_muid'),
    ]

    operations = [
        migrations.AddField(
            model_name='database',
            name='muid',
            field=models.CharField(default='dia', max_length=23),
            preserve_default=False,
        ),
    ]
