# Generated by Django 5.0.6 on 2024-05-16 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cross_asistent', '0006_articulos'),
    ]

    operations = [
        migrations.AddField(
            model_name='banners',
            name='articulo',
            field=models.URLField(default='example.com'),
        ),
    ]
