# Generated by Django 5.0.6 on 2024-08-28 06:14

import cross_asistent.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cross_asistent', '0007_alter_mapa_uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='mapa',
            name='size_marker',
            field=models.CharField(default='0.05', max_length=4),
        ),
        migrations.AlterField(
            model_name='articulos',
            name='encabezado',
            field=models.ImageField(blank=True, max_length=120, null=True, upload_to=cross_asistent.models.set_imgBlog_path),
        ),
        migrations.AlterField(
            model_name='banners',
            name='imagen',
            field=models.ImageField(blank=True, max_length=120, null=True, upload_to=cross_asistent.models.set_imgBanner_path),
        ),
        migrations.AlterField(
            model_name='configuraciones',
            name='about_img_first',
            field=models.ImageField(max_length=120, upload_to=cross_asistent.models.set_conf_path),
        ),
        migrations.AlterField(
            model_name='configuraciones',
            name='about_img_second',
            field=models.ImageField(max_length=120, upload_to=cross_asistent.models.set_conf_path),
        ),
        migrations.AlterField(
            model_name='configuraciones',
            name='qr_image',
            field=models.ImageField(max_length=120, upload_to=cross_asistent.models.set_conf_path),
        ),
        migrations.AlterField(
            model_name='database',
            name='documento',
            field=models.FileField(blank=True, max_length=120, null=True, upload_to=cross_asistent.models.set_pdfDB_path),
        ),
        migrations.AlterField(
            model_name='database',
            name='imagen',
            field=models.ImageField(blank=True, max_length=120, null=True, upload_to=cross_asistent.models.set_imgDB_path),
        ),
        migrations.AlterField(
            model_name='imagenes',
            name='imagen',
            field=models.ImageField(blank=True, max_length=120, null=True, upload_to=cross_asistent.models.set_imgs_path),
        ),
        migrations.AlterField(
            model_name='mapa',
            name='img_marker',
            field=models.ImageField(blank=True, max_length=120, null=True, upload_to=cross_asistent.models.set_imgMarker_path),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='profile_picture',
            field=models.ImageField(blank=True, max_length=120, null=True, upload_to=cross_asistent.models.set_imgProfile_path),
        ),
    ]
