# Generated by Django 5.0.6 on 2024-08-06 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cross_asistent', '0007_database_muid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banners',
            name='descripcion',
            field=models.CharField(blank=True, max_length=350, null=True),
        ),
        migrations.AlterField(
            model_name='banners',
            name='titulo',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
