# Generated by Django 5.0.6 on 2024-08-08 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cross_asistent', '0008_alter_banners_descripcion_alter_banners_titulo'),
    ]

    operations = [
        migrations.AddField(
            model_name='banners',
            name='solo_imagen',
            field=models.BooleanField(default=False),
        ),
    ]
