# Generated by Django 5.0.6 on 2024-05-16 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cross_asistent', '0008_alter_banners_articulo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banners',
            name='articulo',
            field=models.CharField(default=False, max_length=200),
        ),
        migrations.AlterField(
            model_name='banners',
            name='descripcion',
            field=models.CharField(max_length=350),
        ),
        migrations.AlterField(
            model_name='banners',
            name='imagen',
            field=models.ImageField(upload_to='cross_asistent/static/files/banners/'),
        ),
        migrations.AlterField(
            model_name='banners',
            name='titulo',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='preguntas',
            name='documentos',
            field=models.FileField(blank=True, null=True, upload_to='cross_asistent/static/files/documentos/'),
        ),
        migrations.AlterField(
            model_name='preguntas',
            name='imagenes',
            field=models.ImageField(blank=True, null=True, upload_to='cross_asistent/static/files/imagenes/'),
        ),
    ]
