# Generated by Django 5.0.6 on 2024-08-28 17:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cross_asistent', '0008_mapa_size_marker_alter_articulos_encabezado_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Notificacion',
        ),
    ]
