# Generated by Django 5.0.6 on 2024-05-22 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cross_asistent', '0009_alter_banners_articulo_alter_banners_descripcion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banners',
            name='articulo',
            field=models.CharField(default=True, max_length=200, null=True),
        ),
    ]
