# Generated by Django 5.0.6 on 2024-08-09 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cross_asistent', '0009_banners_solo_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='database',
            name='evento_allDay',
            field=models.BooleanField(default=False),
        ),
    ]
