# Generated by Django 5.0.6 on 2024-09-03 19:08

import cross_asistent.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cross_asistent', '0009_delete_notificacion'),
    ]

    operations = [
        migrations.CreateModel(
            name='galeria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(blank=True, max_length=120, null=True, upload_to=cross_asistent.models.set_imgs_path)),
                ('usos', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Imagenes',
        ),
    ]
