# Generated by Django 5.0.6 on 2024-08-13 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cross_asistent', '0010_database_evento_allday'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='blog_firma',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
