# Generated by Django 5.0.6 on 2024-05-22 05:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cross_asistent', '0010_alter_banners_articulo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banners',
            name='articulo',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='banners',
            name='titulo',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='preguntas',
            name='respuesta',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='sugerencias_preg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sugerencia', models.TextField()),
                ('sugerente', models.CharField(default='Anonimo', max_length=100)),
                ('pregunta_num', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cross_asistent.preguntas')),
            ],
        ),
    ]
