# Generated by Django 5.0.6 on 2024-09-05 02:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cross_asistent', '0011_configuraciones_qr_button'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mapa',
            name='img_marker',
        ),
    ]
