# Generated by Django 5.0.6 on 2024-05-22 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cross_asistent', '0011_alter_banners_articulo_alter_banners_titulo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='articulos',
            name='Encabezado',
            field=models.ImageField(blank=True, null=True, upload_to='cross_asistent/static/files/imagenes/'),
        ),
    ]
