# Generated by Django 5.0.6 on 2024-09-05 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cross_asistent', '0012_remove_mapa_img_marker'),
    ]

    operations = [
        migrations.AddField(
            model_name='mapa',
            name='hide_name',
            field=models.BooleanField(default=False),
        ),
    ]
