# Generated by Django 5.0.6 on 2024-09-05 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cross_asistent', '0013_mapa_hide_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mapa',
            name='hide_name',
            field=models.BooleanField(default=True),
        ),
    ]
