# Generated by Django 5.0.6 on 2024-05-24 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cross_asistent', '0014_tareas'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tareas',
            name='completado',
        ),
        migrations.AddField(
            model_name='tareas',
            name='completado_fecha',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tareas',
            name='completar',
            field=models.BooleanField(default=False),
        ),
    ]
