# Generated by Django 5.0.6 on 2024-09-16 22:42

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cross_asistent', '0014_alter_mapa_hide_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='galeria',
            name='uuid',
            field=models.CharField(default=django.utils.timezone.now, max_length=25),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='banners',
            name='expiracion',
            field=models.DateField(blank=True, null=True),
        ),
    ]
