# Generated by Django 5.0.6 on 2024-09-27 01:03

import cross_asistent.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cross_asistent', '0015_galeria_uuid_alter_banners_expiracion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configuraciones',
            name='about_img_first',
            field=models.ImageField(max_length=200, upload_to=cross_asistent.models.set_conf_path),
        ),
        migrations.AlterField(
            model_name='configuraciones',
            name='about_img_second',
            field=models.ImageField(max_length=200, upload_to=cross_asistent.models.set_conf_path),
        ),
        migrations.AlterField(
            model_name='configuraciones',
            name='qr_image',
            field=models.ImageField(max_length=200, upload_to='C:\\Users\\salva\\OneDrive\\Proyectos\\2.WEB\\work\\cross_django\\mediasettings/'),
        ),
    ]
