# Generated by Django 5.0.6 on 2024-09-27 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cross_asistent', '0016_alter_configuraciones_about_img_first_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configuraciones',
            name='qr_image',
            field=models.ImageField(max_length=200, upload_to='settings/'),
        ),
    ]
