# Generated by Django 5.0.6 on 2024-09-27 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cross_asistent', '0017_alter_configuraciones_qr_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configuraciones',
            name='qr_image',
            field=models.FileField(max_length=200, upload_to='settings/'),
        ),
    ]
